/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppDemandRouteImport } from './routes/_app.demand'
import { Route as AppOverviewRouteImport } from './routes/_app.overview'
import { Route as AppDemandForecastExplorerRouteImport } from './routes/_app.demand.forecast-explorer'
import { Route as AppDemandSkusRouteImport } from './routes/_app.demand.skus'
import { Route as AppDemandStoresRouteImport } from './routes/_app.demand.stores'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDemandRoute = AppDemandRouteImport.update({
  id: '/demand',
  path: '/demand',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppDemandForecastExplorerRoute =
  AppDemandForecastExplorerRouteImport.update({
    id: '/forecast-explorer',
    path: '/forecast-explorer',
    getParentRoute: () => AppDemandRoute,
  } as any)
const AppDemandSkusRoute = AppDemandSkusRouteImport.update({
  id: '/skus',
  path: '/skus',
  getParentRoute: () => AppDemandRoute,
} as any)
const AppDemandStoresRoute = AppDemandStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AppDemandRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demand': typeof AppDemandRouteWithChildren
  '/overview': typeof AppOverviewRoute
  '/demand/forecast-explorer': typeof AppDemandForecastExplorerRoute
  '/demand/skus': typeof AppDemandSkusRoute
  '/demand/stores': typeof AppDemandStoresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demand': typeof AppDemandRouteWithChildren
  '/overview': typeof AppOverviewRoute
  '/demand/forecast-explorer': typeof AppDemandForecastExplorerRoute
  '/demand/skus': typeof AppDemandSkusRoute
  '/demand/stores': typeof AppDemandStoresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/demand': typeof AppDemandRouteWithChildren
  '/_app/overview': typeof AppOverviewRoute
  '/_app/demand/forecast-explorer': typeof AppDemandForecastExplorerRoute
  '/_app/demand/skus': typeof AppDemandSkusRoute
  '/_app/demand/stores': typeof AppDemandStoresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demand'
    | '/overview'
    | '/demand/forecast-explorer'
    | '/demand/skus'
    | '/demand/stores'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demand'
    | '/overview'
    | '/demand/forecast-explorer'
    | '/demand/skus'
    | '/demand/stores'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/demand'
    | '/_app/overview'
    | '/_app/demand/forecast-explorer'
    | '/_app/demand/skus'
    | '/_app/demand/stores'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/demand': {
      id: '/_app/demand'
      path: '/demand'
      fullPath: '/demand'
      preLoaderRoute: typeof AppDemandRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/demand/forecast-explorer': {
      id: '/_app/demand/forecast-explorer'
      path: '/forecast-explorer'
      fullPath: '/demand/forecast-explorer'
      preLoaderRoute: typeof AppDemandForecastExplorerRouteImport
      parentRoute: typeof AppDemandRoute
    }
    '/_app/demand/skus': {
      id: '/_app/demand/skus'
      path: '/skus'
      fullPath: '/demand/skus'
      preLoaderRoute: typeof AppDemandSkusRouteImport
      parentRoute: typeof AppDemandRoute
    }
    '/_app/demand/stores': {
      id: '/_app/demand/stores'
      path: '/stores'
      fullPath: '/demand/stores'
      preLoaderRoute: typeof AppDemandStoresRouteImport
      parentRoute: typeof AppDemandRoute
    }
  }
}

interface AppDemandRouteChildren {
  AppDemandForecastExplorerRoute: typeof AppDemandForecastExplorerRoute
  AppDemandSkusRoute: typeof AppDemandSkusRoute
  AppDemandStoresRoute: typeof AppDemandStoresRoute
}

const AppDemandRouteChildren: AppDemandRouteChildren = {
  AppDemandForecastExplorerRoute: AppDemandForecastExplorerRoute,
  AppDemandSkusRoute: AppDemandSkusRoute,
  AppDemandStoresRoute: AppDemandStoresRoute,
}

const AppDemandRouteWithChildren = AppDemandRoute._addFileChildren(
  AppDemandRouteChildren,
)

interface AppRouteChildren {
  AppDemandRoute: typeof AppDemandRouteWithChildren
  AppOverviewRoute: typeof AppOverviewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDemandRoute: AppDemandRouteWithChildren,
  AppOverviewRoute: AppOverviewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
