/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppDemandRouteImport } from './routes/_app.demand'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppOverviewRouteImport } from './routes/_app.overview'
import { Route as AppDemandAccuracyRouteImport } from './routes/_app.demand.accuracy'
import { Route as AppDemandDriversRouteImport } from './routes/_app.demand.drivers'
import { Route as AppDemandForecastExplorerRouteImport } from './routes/_app.demand.forecast-explorer'
import { Route as AppDemandSkusRouteImport } from './routes/_app.demand.skus'
import { Route as AppDemandStoresRouteImport } from './routes/_app.demand.stores'
import { Route as AppInventoryBalanceRouteImport } from './routes/_app.inventory.balance'
import { Route as AppInventoryExcessRouteImport } from './routes/_app.inventory.excess'
import { Route as AppInventoryReplenishmentRouteImport } from './routes/_app.inventory.replenishment'
import { Route as AppInventoryStockRiskRouteImport } from './routes/_app.inventory.stock-risk'
import { Route as AppInventoryTransfersRouteImport } from './routes/_app.inventory.transfers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDemandRoute = AppDemandRouteImport.update({
  id: '/demand',
  path: '/demand',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppDemandAccuracyRoute = AppDemandAccuracyRouteImport.update({
  id: '/accuracy',
  path: '/accuracy',
  getParentRoute: () => AppDemandRoute,
} as any)
const AppDemandDriversRoute = AppDemandDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AppDemandRoute,
} as any)
const AppDemandForecastExplorerRoute =
  AppDemandForecastExplorerRouteImport.update({
    id: '/forecast-explorer',
    path: '/forecast-explorer',
    getParentRoute: () => AppDemandRoute,
  } as any)
const AppDemandSkusRoute = AppDemandSkusRouteImport.update({
  id: '/skus',
  path: '/skus',
  getParentRoute: () => AppDemandRoute,
} as any)
const AppDemandStoresRoute = AppDemandStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AppDemandRoute,
} as any)
const AppInventoryBalanceRoute = AppInventoryBalanceRouteImport.update({
  id: '/balance',
  path: '/balance',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryExcessRoute = AppInventoryExcessRouteImport.update({
  id: '/excess',
  path: '/excess',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryReplenishmentRoute =
  AppInventoryReplenishmentRouteImport.update({
    id: '/replenishment',
    path: '/replenishment',
    getParentRoute: () => AppInventoryRoute,
  } as any)
const AppInventoryStockRiskRoute = AppInventoryStockRiskRouteImport.update({
  id: '/stock-risk',
  path: '/stock-risk',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryTransfersRoute = AppInventoryTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AppInventoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demand': typeof AppDemandRouteWithChildren
  '/inventory': typeof AppInventoryRouteWithChildren
  '/overview': typeof AppOverviewRoute
  '/demand/accuracy': typeof AppDemandAccuracyRoute
  '/demand/drivers': typeof AppDemandDriversRoute
  '/demand/forecast-explorer': typeof AppDemandForecastExplorerRoute
  '/demand/skus': typeof AppDemandSkusRoute
  '/demand/stores': typeof AppDemandStoresRoute
  '/inventory/balance': typeof AppInventoryBalanceRoute
  '/inventory/excess': typeof AppInventoryExcessRoute
  '/inventory/replenishment': typeof AppInventoryReplenishmentRoute
  '/inventory/stock-risk': typeof AppInventoryStockRiskRoute
  '/inventory/transfers': typeof AppInventoryTransfersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demand': typeof AppDemandRouteWithChildren
  '/inventory': typeof AppInventoryRouteWithChildren
  '/overview': typeof AppOverviewRoute
  '/demand/accuracy': typeof AppDemandAccuracyRoute
  '/demand/drivers': typeof AppDemandDriversRoute
  '/demand/forecast-explorer': typeof AppDemandForecastExplorerRoute
  '/demand/skus': typeof AppDemandSkusRoute
  '/demand/stores': typeof AppDemandStoresRoute
  '/inventory/balance': typeof AppInventoryBalanceRoute
  '/inventory/excess': typeof AppInventoryExcessRoute
  '/inventory/replenishment': typeof AppInventoryReplenishmentRoute
  '/inventory/stock-risk': typeof AppInventoryStockRiskRoute
  '/inventory/transfers': typeof AppInventoryTransfersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/demand': typeof AppDemandRouteWithChildren
  '/_app/inventory': typeof AppInventoryRouteWithChildren
  '/_app/overview': typeof AppOverviewRoute
  '/_app/demand/accuracy': typeof AppDemandAccuracyRoute
  '/_app/demand/drivers': typeof AppDemandDriversRoute
  '/_app/demand/forecast-explorer': typeof AppDemandForecastExplorerRoute
  '/_app/demand/skus': typeof AppDemandSkusRoute
  '/_app/demand/stores': typeof AppDemandStoresRoute
  '/_app/inventory/balance': typeof AppInventoryBalanceRoute
  '/_app/inventory/excess': typeof AppInventoryExcessRoute
  '/_app/inventory/replenishment': typeof AppInventoryReplenishmentRoute
  '/_app/inventory/stock-risk': typeof AppInventoryStockRiskRoute
  '/_app/inventory/transfers': typeof AppInventoryTransfersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demand'
    | '/inventory'
    | '/overview'
    | '/demand/accuracy'
    | '/demand/drivers'
    | '/demand/forecast-explorer'
    | '/demand/skus'
    | '/demand/stores'
    | '/inventory/balance'
    | '/inventory/excess'
    | '/inventory/replenishment'
    | '/inventory/stock-risk'
    | '/inventory/transfers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demand'
    | '/inventory'
    | '/overview'
    | '/demand/accuracy'
    | '/demand/drivers'
    | '/demand/forecast-explorer'
    | '/demand/skus'
    | '/demand/stores'
    | '/inventory/balance'
    | '/inventory/excess'
    | '/inventory/replenishment'
    | '/inventory/stock-risk'
    | '/inventory/transfers'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/demand'
    | '/_app/inventory'
    | '/_app/overview'
    | '/_app/demand/accuracy'
    | '/_app/demand/drivers'
    | '/_app/demand/forecast-explorer'
    | '/_app/demand/skus'
    | '/_app/demand/stores'
    | '/_app/inventory/balance'
    | '/_app/inventory/excess'
    | '/_app/inventory/replenishment'
    | '/_app/inventory/stock-risk'
    | '/_app/inventory/transfers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/demand': {
      id: '/_app/demand'
      path: '/demand'
      fullPath: '/demand'
      preLoaderRoute: typeof AppDemandRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/demand/accuracy': {
      id: '/_app/demand/accuracy'
      path: '/accuracy'
      fullPath: '/demand/accuracy'
      preLoaderRoute: typeof AppDemandAccuracyRouteImport
      parentRoute: typeof AppDemandRoute
    }
    '/_app/demand/drivers': {
      id: '/_app/demand/drivers'
      path: '/drivers'
      fullPath: '/demand/drivers'
      preLoaderRoute: typeof AppDemandDriversRouteImport
      parentRoute: typeof AppDemandRoute
    }
    '/_app/demand/forecast-explorer': {
      id: '/_app/demand/forecast-explorer'
      path: '/forecast-explorer'
      fullPath: '/demand/forecast-explorer'
      preLoaderRoute: typeof AppDemandForecastExplorerRouteImport
      parentRoute: typeof AppDemandRoute
    }
    '/_app/demand/skus': {
      id: '/_app/demand/skus'
      path: '/skus'
      fullPath: '/demand/skus'
      preLoaderRoute: typeof AppDemandSkusRouteImport
      parentRoute: typeof AppDemandRoute
    }
    '/_app/demand/stores': {
      id: '/_app/demand/stores'
      path: '/stores'
      fullPath: '/demand/stores'
      preLoaderRoute: typeof AppDemandStoresRouteImport
      parentRoute: typeof AppDemandRoute
    }
    '/_app/inventory/balance': {
      id: '/_app/inventory/balance'
      path: '/balance'
      fullPath: '/inventory/balance'
      preLoaderRoute: typeof AppInventoryBalanceRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/excess': {
      id: '/_app/inventory/excess'
      path: '/excess'
      fullPath: '/inventory/excess'
      preLoaderRoute: typeof AppInventoryExcessRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/replenishment': {
      id: '/_app/inventory/replenishment'
      path: '/replenishment'
      fullPath: '/inventory/replenishment'
      preLoaderRoute: typeof AppInventoryReplenishmentRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/stock-risk': {
      id: '/_app/inventory/stock-risk'
      path: '/stock-risk'
      fullPath: '/inventory/stock-risk'
      preLoaderRoute: typeof AppInventoryStockRiskRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/transfers': {
      id: '/_app/inventory/transfers'
      path: '/transfers'
      fullPath: '/inventory/transfers'
      preLoaderRoute: typeof AppInventoryTransfersRouteImport
      parentRoute: typeof AppInventoryRoute
    }
  }
}

interface AppDemandRouteChildren {
  AppDemandAccuracyRoute: typeof AppDemandAccuracyRoute
  AppDemandDriversRoute: typeof AppDemandDriversRoute
  AppDemandForecastExplorerRoute: typeof AppDemandForecastExplorerRoute
  AppDemandSkusRoute: typeof AppDemandSkusRoute
  AppDemandStoresRoute: typeof AppDemandStoresRoute
}

const AppDemandRouteChildren: AppDemandRouteChildren = {
  AppDemandAccuracyRoute: AppDemandAccuracyRoute,
  AppDemandDriversRoute: AppDemandDriversRoute,
  AppDemandForecastExplorerRoute: AppDemandForecastExplorerRoute,
  AppDemandSkusRoute: AppDemandSkusRoute,
  AppDemandStoresRoute: AppDemandStoresRoute,
}

const AppDemandRouteWithChildren = AppDemandRoute._addFileChildren(
  AppDemandRouteChildren,
)

interface AppInventoryRouteChildren {
  AppInventoryBalanceRoute: typeof AppInventoryBalanceRoute
  AppInventoryExcessRoute: typeof AppInventoryExcessRoute
  AppInventoryReplenishmentRoute: typeof AppInventoryReplenishmentRoute
  AppInventoryStockRiskRoute: typeof AppInventoryStockRiskRoute
  AppInventoryTransfersRoute: typeof AppInventoryTransfersRoute
}

const AppInventoryRouteChildren: AppInventoryRouteChildren = {
  AppInventoryBalanceRoute: AppInventoryBalanceRoute,
  AppInventoryExcessRoute: AppInventoryExcessRoute,
  AppInventoryReplenishmentRoute: AppInventoryReplenishmentRoute,
  AppInventoryStockRiskRoute: AppInventoryStockRiskRoute,
  AppInventoryTransfersRoute: AppInventoryTransfersRoute,
}

const AppInventoryRouteWithChildren = AppInventoryRoute._addFileChildren(
  AppInventoryRouteChildren,
)

interface AppRouteChildren {
  AppDemandRoute: typeof AppDemandRouteWithChildren
  AppInventoryRoute: typeof AppInventoryRouteWithChildren
  AppOverviewRoute: typeof AppOverviewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDemandRoute: AppDemandRouteWithChildren,
  AppInventoryRoute: AppInventoryRouteWithChildren,
  AppOverviewRoute: AppOverviewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
